name: Test Execution

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Run environment"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - qa
      cucumber_tags:
        description: "Cucumber tags to run"
        required: true
        default: "@regression"
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - name: Send Test Started Notification to Slack
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   run: |
      #     curl -X POST -H 'Content-type: application/json' --data "{\"text\":\":large_blue_circle: Test Execution Started.\"}" $SLACK_WEBHOOK_URL

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Cucumber tests
        id: run_tests
        run: |
          npx cucumber-js --tags '${{ github.event.inputs.cucumber_tags || '@regression' }}' --world-parameters '{"headless": true, "environment": "${{ github.event.inputs.environment || 'production' }}"}'
          echo "exit_code=$?" >> $GITHUB_ENV
        continue-on-error: true

      - name: Generate Allure report
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Configure Git
        run: |
          git config --global user.email "surendaranpalani@gmail.com"
          git config --global user.name "Suren220695"

      - name: Create and commit GitHub Pages branch
        run: |
          git add .
          git checkout --orphan gh-pages
          git commit -m "Deploy Allure report to GitHub Pages"
          git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git push -f origin gh-pages

      - name: Clean up
        run: |
          git checkout main
          git branch -D gh-pages

      - name: Set test result output
        id: set_test_result
        run: |
          if [[ "${{ env.exit_code }}" == "0" ]]; then
            echo "TEST_STATUS=passed" >> $GITHUB_ENV
            echo "::set-output name=TEST_STATUS::passed"
          else
            echo "TEST_STATUS=failed" >> $GITHUB_ENV
            echo "::set-output name=TEST_STATUS::failed"
          fi
    outputs:
      TEST_STATUS: ${{ steps.set_test_result.outputs.TEST_STATUS }}

  # notify:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Retrieve test status
  #       id: get_test_status
  #       run: echo "TEST_STATUS=${{ needs.test.outputs.TEST_STATUS }}" >> $GITHUB_ENV

  #     - name: Send Slack notification
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         GITHUB_PAGES_URL: "https://${{ github.repository_owner }}.github.io/qa-automation/allure-report"
  #         TEST_STATUS: ${{ env.TEST_STATUS }}

  #       run: |
  #         if [[ "${{ env.TEST_STATUS }}" == "passed" ]]; then
  #           MESSAGE=":large_green_circle: Test Execution Completed! Tests passed. View the report at: $GITHUB_PAGES_URL"
  #         else
  #           MESSAGE=":red_circle: Test Execution Completed! Tests failed. View the report at: $GITHUB_PAGES_URL"
  #         fi
  #         curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${MESSAGE}\"}" $SLACK_WEBHOOK_URL
